### ISSUE TITLE
Add better support for PGN: move numbering

### ISSUE THREAD

**Issue by CiceroIsBack** [r8/logseq-chess#10]
PGN notation typically requires that each pair of moves be labeled with its move number (e.g. `1. e4 e5 2. Nf3 Nc6` etc). 

However, the logseq-chess plugin does not allow for numbering moves. It currently requires that the numbers be taken out before the parser can understand what is going on (e.g. `e4 e5 Nf3 Nc6`). This forces the extra friction of removing that data on the user, and makes this plugin less standards-compliant.

Adding support for this should be a trivial change in the [parseMoves()](https://github.com/r8/logseq-chess/blob/c03f4323bbefcc3ea635f23010fd739c8e48b003/src/parsers/chess/chessConfig.ts#L111) function in the chess parser file. (At least, I think so. I haven't looked deeply into it yet). 

Is adding support for this something that the devs are interested in? If so, I am very willing to implement it and make a PR. 

(See PGN standards documentation [here](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm), especially the [sample pgn file](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c2.3))

**Comment by r8** [comment]
Hey @CiceroIsBack 

PGN mode is very much in the scope and actually the work on it is in progress, so stay tuned.

I was thinking about the current moves mode as a way to embed a simple position or a combination of moves.

PGN is about the complete game, with possible variants and comments, so I'm trying to do a more sophisticated widget, something like [Lichess PGN embed](https://github.com/lichess-org/pgn-viewer), but a bit simpler.

**Comment by CiceroIsBack** [comment]
Ah, I see. So the idea is to have a simple mode and a complex mode? So with the current widget you can embed a simple position; then with the more sophisticated PGN widget, you can embed a whole game?

I actually like that idea a lot. You don't need a complex widget when all you want to show is a position. 
Also, after using the plugin some more I think the widget as it currently is will be sufficient for most of my uses. But I'm definitely excited to get to embed full games :)
